f = figure(1);
f.Units = 'normalized';
f.Position(4) = 0.6; % height

colordef none
clf reset
whitebg(gcf,[0 0 0])
set(gcf,'Units','normalized','Name','CMAC Simulation')

ax_mem = axes('Position',[0.05 0.52 0.40 0.45]);
if bucket_mode == 1
  h_mem = surf(0:63,0:63,zeros(64));
  view([0 90])
  axis([0 63 0 63]), axis off, axis equal
  caxis([-0.01,0.01])
else
  % For sequential mode, show the full CMAC memory just like random mode
  h_mem = surf(0:63,0:63,zeros(64));
  view([0 90])
  axis([0 63 0 63]), axis off, axis equal
  caxis([-0.01,0.01])
end
colormap jet

ax_out = axes('Position',[0.55 0.5 0.40 0.45]);
hold on
h_desired = plot(xcoords,ycoords,':','Color','c');
h_out = plot(xcoords,0*xcoords,'Color','w');
axis([0 360 -1.3 1.3])
axis off

ax_in = axes('Position',[0.15 0.30 0.75 0.18]);
hold on
h_in = plot(xcoords,ycoords,'g');
axis([0 360 -1.2 1.2])
box off
set(ax_in,'Xtick',[0 90 180 270 360])
set(ax_in,'ButtonDownFcn','clickhandler')
set(h_in,'ButtonDownFcn','clickhandler')
title('Click on the green curve to sample data points','Color','g')

% --- Create axes for Tiling/Bucket Visualization ---
ax_hist = axes('Position',[0.15 0.15 0.75 0.10]);
hold on;
xlabel('Buckets in Input Space (0-359)');
ylabel('Hash #');
set(ax_hist, 'YDir', 'reverse'); % Puts hash 1 at the top
axis([0 359 0 Nhashes+1]);
box on;
set(ax_hist, 'XColor', 'w', 'YColor', 'w');

% --- Draw the buckets for each hash ---
g_h_hist_bars = cell(Nhashes * Nbuckets_per_hash, 1);
bmin_matrix = mod(reshape(bmin, Nhashes, Nbuckets_per_hash), 360);
bmax_matrix = mod(reshape(bmax, Nhashes, Nbuckets_per_hash), 360);
inactive_color = [0.4 0.4 0.4];

for i = 1:Nhashes
  for j = 1:Nbuckets_per_hash
    x_min = bmin_matrix(i,j);
    x_max = bmax_matrix(i,j);
    y_pos = i - 0.4;
    height = 0.8;

    idx = sub2ind([Nhashes, Nbuckets_per_hash], i, j);

    if x_min > x_max % Handle wrap-around buckets
      % Draw part 1 (from x_min to end)
      p1 = patch([x_min 359 359 x_min], [y_pos y_pos y_pos+height y_pos+height], inactive_color);
      % Draw part 2 (from start to x_max)
      p2 = patch([0 x_max x_max 0], [y_pos y_pos y_pos+height y_pos+height], inactive_color);
      g_h_hist_bars{idx} = [p1, p2];
    else
      p = patch([x_min x_max x_max x_min], [y_pos y_pos y_pos+height y_pos+height], inactive_color);
      g_h_hist_bars{idx} = p;
    end
  end
end

reset_button = ...
    uicontrol('Style','Pushbutton', ...
	      'Units','Pixels', 'Position',[3 3 60 20], ...
	      'BackgroundColor',[1 0.6 0.6],'String','Reset', ...
	      'Callback','reset_cmac');

sample_button = ...
    uicontrol('Style','Pushbutton', ...
	      'Units','Pixels', 'Position',[70 3 60 20], ...
	      'BackgroundColor',[1 1 0],'String','Sample', ...
	      'CallBack','sample_point;plot_cmac');

sample_10_button = ...
    uicontrol('Style','Pushbutton', ...
	      'Units','Pixels', 'Position',[140 3 60 20], ...
	      'BackgroundColor',[1 1 0],'String','x 10', ...
	      'CallBack','for i=1:10,sample_point,end,plot_cmac');

function_menu = ...
    uicontrol('Style','Popup', ...
	      'Units','Pixels', 'Position',[220 3 80 20], ...
	      'BackgroundColor',[0.2 1 0.2], ...
	      'String',{'sin(x)','sin(3x)','sin(8x)','steps','random'}, ...
	      'CallBack','setup_data_points');

train_button = ...
    uicontrol('Style','Pushbutton', ...
	      'Units','Pixels', 'Position',[310 3 70 20], ...
	      'BackgroundColor',[1 1 0],'String','Rehearse', ...
	      'CallBack','for i=1:size(training_points,1),pcoords=training_points(i,:);train_point,end,plot_cmac');

bucketmode_menu = ...
    uicontrol('Style','Popup', ...
	      'Units','Pixels', 'Position',[390 3 80 20], ...
	      'BackgroundColor',[0.2 1 0.2], ...
	      'String',{'Rand','Seq'}, ...
	      'Value',bucket_mode, ...
	      'CallBack','set_bucketmode');

% --- Define a bottom margin for this new row of controls ---
param_row_y = 33;

% --- N Hashes ---
uicontrol('Style','text', 'Position',[10 param_row_y 60 20], ...
          'BackgroundColor',[0 0 0], 'ForegroundColor',[0.8 0.8 1], ...
          'String','N Hashes:');
uicontrol('Style','edit', 'Position',[75 param_row_y 40 20], ...
          'String',num2str(Nhashes), ...
          'BackgroundColor',[0.8 0.8 1], ...
          'Tag','nhashes_box', ...
          'Callback','update_cmac_params');

% --- Buckets/Hash ---
uicontrol('Style','text', 'Position',[125 param_row_y 85 20], ...
          'BackgroundColor',[0 0 0], 'ForegroundColor',[0.8 0.8 1], ...
          'String','N Buckets/Hash:');
uicontrol('Style','edit', 'Position',[215 param_row_y 40 20], ...
          'String',num2str(Nbuckets_per_hash), ...
          'BackgroundColor',[0.8 0.8 1], ...
          'Tag','nbuckets_box', ...
          'Callback','update_cmac_params');

% --- Hash Stride ---
uicontrol('Style','text', 'Position',[265 param_row_y 70 20], ...
          'BackgroundColor',[0 0 0], 'ForegroundColor',[0.8 0.8 1], ...
          'String','Hash Stride(°):');
uicontrol('Style','edit', 'Position',[340 param_row_y 40 20], ...
          'String',num2str(hash_stride), ...
          'BackgroundColor',[0.8 0.8 1], ...
          'Tag','hashstride_box', ...
          'Callback','update_cmac_params');

% --- Learning Rate (Re-created and moved for horizontal alignment) ---
uicontrol('Style','Text', ...
          'Units','Pixels', 'Position',[390 param_row_y 80 20], ...
          'BackgroundColor',[0 0 0], 'ForegroundColor',[0.8 0.8 1], ...
          'String','Learning rate:');
uicontrol('Style','Edit', ...
          'Units','Pixels', 'Position',[475 param_row_y 50 20], ...
          'BackgroundColor',[0.8 0.8 1], ...
          'String',num2str(g_val), ...
          'CallBack','set_g_value');
